name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Configurar Gradle 9.3.1 en el sistema
      run: |
        wget https://services.gradle.org/distributions/gradle-9.3.1-bin.zip
        sudo unzip -d /opt/gradle gradle-9.3.1-bin.zip
        echo "/opt/gradle/gradle-9.3.1/bin" >> $GITHUB_PATH

    - name: Generar wrapper con Gradle 9.3.1 y dar permisos
      run: |
        /opt/gradle/gradle-9.3.1/bin/gradle wrapper --gradle-version 9.3.1
        chmod +x gradlew

    - name: Compilar APK Debug
      run: ./gradlew assembleDebug --stacktrace

    - name: Subir APK como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
