name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Validar permisos de gradlew
      run: |
        if [ -f gradlew ]; then
          chmod +x gradlew
        else
          gradle wrapper
          chmod +x gradlew
        fi

    - name: Compilar APK Debug
      run: ./gradlew assembleDebug

    - name: Subir APK como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
